In [2]:
import pandas as pd
import numpy as np

In [153]:
reportsjan_feb =pd.read_excel("For_Pandas_Original_DF.xlsx", sheet_name = "внешный")
jan_feb_2022_reports = pd.read_excel("For_Pandas_Original_DF.xlsx")
reportsjan_feb.head(2)
#reportsjan_feb.dtypes

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN

In [158]:
# I want to delete only rows that have the name "Внш Давид"
delete_david = reportsjan_feb["Поставщик"]== "Внш Давид"
reportsjan_feb.drop(index= reportsjan_feb[delete_david].index)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
13,27868.0,2022-01-01,1.0,Внш Хувайдо,Футеровка (№ черт. 02.590.00.01) 591,18812.0,Стройматериал,шт,24.0,9792.500000,2.350200e+05,NaT,NaN,"ООО ""ФАРАМИ ГРУПП"", Москва Контракт:№ФГ/ЕКБ-0...",NaN,Рогун УБР,NaN
14,27868.0,2022-01-01,1.0,Внш Хувайдо,Футеровка (№ черт. 02.590.00.02) 592,18813.0,Стройматериал,шт,24.0,11112.299805,2.666952e+05,NaT,NaN,"ООО ""ФАРАМИ ГРУПП"", Москва Контракт:№ФГ/ЕКБ-0...",NaN,Рогун УБР,NaN
15,27868.0,2022-01-01,1.0,Внш Хувайдо,Футеровка (№ черт. 02.590.00.03) 593,18814.0,Стройматериал,шт,24.0,9792.500000,2.350200e+05,NaT,NaN,"ООО ""ФАРАМИ ГРУПП"", Москва Контракт:№ФГ/ЕКБ-0...",NaN,Рогун УБР,NaN
16,27868.0,2022-01-01,1.0,Внш Хувайдо,Футеровка торцевая ( № черт. 1348.02.201СБ) 201,18815.0,Стройматериал,шт,16.0,7719.799805,1.235168e+05,NaT,NaN,"ООО ""ФАРАМИ ГРУПП"", Москва Контракт:№ФГ/ЕКБ-0...",NaN,Рогун УБР,NaN
17,27868.0,2022-01-01,1.0,Внш Хувайдо,Болт футеровочный М36х4х200,18816.0,Стройматериал,шт,184.0,176.399994,3.245760e+04,NaT,NaN,"ООО ""ФАРАМИ ГРУПП"", Москва Контракт:№ФГ/ЕКБ-0...",NaN,Рогун УБР,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,28896.0,2022-02-22,1.0,Внш Хайруллоев Боир,Заземление переносное ЗПП-1-3/3-16,30470.0,Электроматериалы,комп,12.0,1250.000000,1.500000e+04,NaT,NaN,"ООО ""Элпартнер"" Счет №ТП-188 от 22.12.2021г.",NaN,АСКУЭ+,NaN
255,28898.0,2022-02-28,1.0,Внш Хайруллоев Боир,Полипласт СП-1ВП,30925.0,Стройматериал,т,20.0,23550.000000,4.710000e+05,NaT,NaN,"ООО ""Полипласт-Уралсиб"" Контракт:№001/2020 от ...",NaN,Рогун УБР,NaN
256,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.617372e+07,NaT,NaN,NaN,NaN,NaN,NaN
257,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.650796e+07,NaT,NaN,NaN,NaN,NaN,NaN
258,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.304390e+05,NaT,NaN,NaN,NaN,NaN,NaN

In [152]:
# Drop index, rows not columns
reportsjan_feb.drop(index=[0],inplace=True)

In [ ]:
# Adding values from tbl A to tbl B, that's what I am stuck at?!

In [147]:
# Add a new row of data via .append()
reportsjan_feb.append({"Поставщик":"Anushervon"},ignore_index=True)

C:\Users\User-PC\AppData\Local\Temp\ipykernel_4036\2967647725.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  reportsjan_feb.append({"Поставщик":"Anushervon"},ignore_index=True)

AttributeError: 'DataFrame' object has no attribute 'concat'

In [140]:
# Add Multiple Columns in a one line of code
reportsjan_feb[["Name1","Name2""Name3"]] = reportsjan_feb["Сумма"] /reportsjan_feb["Сумма"].sum()
reportsjan_feb.head()

ValueError: Columns must be same length as key

In [136]:
# Drop not needed columns
reportsjan_feb.drop(columns=["Unnamed: 16"],inplace=True)
reportsjan_feb.head(2)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм

In [130]:
# Let's add a new column
reportsjan_feb["Name_Splitted"] = reportsjan_feb["Наименование"].str.split(expand=True)[0]
reportsjan_feb.head(3)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16,Name_Splitted
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN,Трансформатор
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN,Трансформатор
2,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 100/6кВТ,30365.0,Электроматериалы,шт,1.0,42275.0,42275.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Себистон,NaN,Трансформатор

In [117]:
# Changing the values of the columns
#reportsjan_feb["Тов группа"].value_counts()
reportsjan_feb["Тов группа"] = reportsjan_feb["Тов группа"].map({"Электроматериалы": "Electronic_materials","Стройматериал":"Construction_materials","Инструмент": "Instruments"})
reportsjan_feb.head()

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Electronic_materials,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Electronic_materials,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
2,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 100/6кВТ,30365.0,Electronic_materials,шт,1.0,42275.0,42275.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Себистон,NaN
3,27655.0,2022-01-01,2.0,Внш Давид,Компас Горно геологический ГГК,30362.0,NaN,шт,5.0,2700.0,13500.0,NaT,NaN,ООО СПЕЦСНАБ ПГС Счет №21122010 от 20.12.2021,NaN,Рогун УБР,NaN
4,27656.0,2022-01-01,3.0,Внш Давид,Преобразователь ИД3,30358.0,Electronic_materials,шт,1.0,4070.0,4070.0,NaT,NaN,ООО КОНСТАНТА Счет №2316 от 14 декабря 2021 г.,NaN,Кайрокум,NaN

In [107]:
# Rename two columns from the DF
reportsjan_feb.rename(columns={"Дата":"Date", "Поставщик":"International_Supplier"},inplace=True)
reportsjan_feb.head(2)

,Код,Date,№ док,International_Supplier,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN

In [98]:
# What if I want to change a row from specific column to another row -- ????
reportsjan_feb[0,"Наименование"] = reportsjan_feb["Наименование"].map({"Трансформатор ТМГ 250/10кВТ": "Трансформатор ТМГ 350/10кВТ"})

In [87]:
reportsjan_feb["Поставщик"].apply(make_lower("Вопросы=Anush"))

AttributeError: 'ВОПРОСЫ=ANUSH' is not a valid function for 'Series' object

In [81]:
reportsjan_feb.apply(len)

Код             259
Дата            259
№ док           259
Поставщик       259
Наименование    259
Абрев           259
Тов группа      259
Ед Изм          259
Кол-во          259
Цена            259
Сумма           259
Срок            259
Серия           259
Произ.          259
МНН             259
Вопросы         259
Unnamed: 16     259
dtype: int64

In [79]:

## Apply a function to the DF # Our funtion didn't work out as I wanted

def make_lower(Вопросы):
    return Вопросы.upper()
##
reportsjan_feb["Наименование"].apply(make_lower)

AttributeError: 'float' object has no attribute 'upper'

In [63]:
# How to make the whole rows from a specific column to lowercase() or uppercase()
reportsjan_feb["Поставщик"] = reportsjan_feb["Поставщик"].str.upper()
reportsjan_feb.head()

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,ВНШ ДАВИД,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,ВНШ ДАВИД,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
2,27654.0,2022-01-01,1.0,ВНШ ДАВИД,Трансформатор ТМГ 100/6кВТ,30365.0,Электроматериалы,шт,1.0,42275.0,42275.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Себистон,NaN
3,27655.0,2022-01-01,2.0,ВНШ ДАВИД,Компас Горно геологический ГГК,30362.0,Ос Средства,шт,5.0,2700.0,13500.0,NaT,NaN,ООО СПЕЦСНАБ ПГС Счет №21122010 от 20.12.2021,NaN,Рогун УБР,NaN
4,27656.0,2022-01-01,3.0,ВНШ ДАВИД,Преобразователь ИД3,30358.0,Электроматериалы,шт,1.0,4070.0,4070.0,NaT,NaN,ООО КОНСТАНТА Счет №2316 от 14 декабря 2021 г.,NaN,Кайрокум,NaN

In [55]:
# Let's assume that I want to change from 1st to 10th rows, from multiple columns --n???
reportsjan_feb.loc[([1:10]),["Тов группа","Произ."]] = ["Construction_Materials","LLC. Charkhi Gardun"]
reportsjan_feb.head(10)

SyntaxError: invalid syntax (1349903637.py, line 2)

In [48]:
# Let's assume that I want to change several rows from multiple columns
reportsjan_feb.loc[[0,1],["Тов группа","Произ."]] = ["Construction_Materials","LLC. Charkhi Gardun"]
reportsjan_feb.head(2)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Construction_Materials,шт,1.0,65770.0,65770.0,NaT,NaN,LLC. Charkhi Gardun,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Construction_Materials,шт,1.0,118255.0,118255.0,NaT,NaN,LLC. Charkhi Gardun,NaN,Нуробод Оби гарм,NaN

In [46]:
# What if I want to changea row from multiple columns
reportsjan_feb.loc[1,["Тов группа","Произ."]] = ["Construction_Materials","LLC. Charkhi Gardun"]
reportsjan_feb.head(2)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Construction_Materials,шт,1.0,118255.0,118255.0,NaT,NaN,LLC. Charkhi Gardun,NaN,Нуробод Оби гарм,NaN

In [43]:
# How to change a row from a specific column
reportsjan_feb.loc[1,"Поставщик"] ="Внш_Маха"
reportsjan_feb.head(2)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш_Маха,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN

In [39]:
# Let's update a specific row
reportsjan_feb.loc[1] = ['202020', "2020-01-2012", "2.0", "Внш Anush", "Трансформатор ТМГ 230/10кВТ", "	30354.0", "Электроматериалы", "шт", "5", "122255.0","118255.0", "NaT", "NaN", "Чирчикский трансформаторный завод Контракт:TG..", "NaN", "Нуробод Оби гарм", "NaN"]
reportsjan_feb.head(2)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01 00:00:00,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,202020,2020-01-2012,2.0,Внш Anush,Трансформатор ТМГ 230/10кВТ,\t30354.0,Электроматериалы,шт,5,122255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG..,NaN,Нуробод Оби гарм,NaN

In [35]:
# Get a specific row
reportsjan_feb.loc[1]

Код                                                       27654.0
Дата                                          2022-01-01 00:00:00
№ док                                                         1.0
Поставщик                                               Внш Давид
Наименование                          Трансформатор ТМГ 630/10кВТ
Абрев                                                     30364.0
Тов группа                                       Электроматериалы
Ед Изм                                                         шт
Кол-во                                                        1.0
Цена                                                     118255.0
Сумма                                                    118255.0
Срок                                                          NaT
Серия                                                         NaN
Произ.          Чирчикский трансформаторный завод  Контракт:TG...
МНН                                                           NaN
Вопросы                                          Нуробод Оби гарм
Unnamed: 16                                                   NaN
Name: 1, dtype: object

In [26]:
## Add "_" instead of spaces
reportsjan_feb.columns.str.replace(" ", "_")

Index(['Код', 'Дата', '№_док', 'Поставщик', 'Наименование', 'Абрев',
       'Тов_группа', 'Ед_Изм', 'Кол-во', 'Цена', 'Сумма', 'Срок_', 'Серия',
       'Произ.', 'МНН', 'Вопросы', 'Unnamed:_16'],
      dtype='object')

In [24]:
# Rename column names
# For instance
reportsjan_feb.rename(columns={"Дата": "Date","Поставщик":"International_Supplier" })

,Код,Date,№ док,International_Supplier,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,6.577000e+04,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,1.182550e+05,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
2,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 100/6кВТ,30365.0,Электроматериалы,шт,1.0,42275.0,4.227500e+04,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Себистон,NaN
3,27655.0,2022-01-01,2.0,Внш Давид,Компас Горно геологический ГГК,30362.0,Ос Средства,шт,5.0,2700.0,1.350000e+04,NaT,NaN,ООО СПЕЦСНАБ ПГС Счет №21122010 от 20.12.2021,NaN,Рогун УБР,NaN
4,27656.0,2022-01-01,3.0,Внш Давид,Преобразователь ИД3,30358.0,Электроматериалы,шт,1.0,4070.0,4.070000e+03,NaT,NaN,ООО КОНСТАНТА Счет №2316 от 14 декабря 2021 г.,NaN,Кайрокум,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
254,28896.0,2022-02-22,1.0,Внш Хайруллоев Боир,Заземление переносное ЗПП-1-3/3-16,30470.0,Электроматериалы,комп,12.0,1250.0,1.500000e+04,NaT,NaN,"ООО ""Элпартнер"" Счет №ТП-188 от 22.12.2021г.",NaN,АСКУЭ+,NaN
255,28898.0,2022-02-28,1.0,Внш Хайруллоев Боир,Полипласт СП-1ВП,30925.0,Стройматериал,т,20.0,23550.0,4.710000e+05,NaT,NaN,"ООО ""Полипласт-Уралсиб"" Контракт:№001/2020 от ...",NaN,Рогун УБР,NaN
256,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.617372e+07,NaT,NaN,NaN,NaN,NaN,NaN
257,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.650796e+07,NaT,NaN,NaN,NaN,NaN,NaN
258,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7.304390e+05,NaT,NaN,NaN,NaN,NaN,NaN

In [19]:
# Use comprehesion to change all columns Names to uppercase
# Use comprehesion to change all columns Names to lowercase

#reportsjan_feb.columns= [x.upper() for x in reportsjan_feb.columns]
reportsjan_feb.columns= [x.lower() for x in reportsjan_feb.columns]
reportsjan_feb.head()

,код,дата,№ док,поставщик,наименование,абрев,тов группа,ед изм,кол-во,цена,сумма,срок,серия,произ.,мнн,вопросы,unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
2,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 100/6кВТ,30365.0,Электроматериалы,шт,1.0,42275.0,42275.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Себистон,NaN
3,27655.0,2022-01-01,2.0,Внш Давид,Компас Горно геологический ГГК,30362.0,Ос Средства,шт,5.0,2700.0,13500.0,NaT,NaN,ООО СПЕЦСНАБ ПГС Счет №21122010 от 20.12.2021,NaN,Рогун УБР,NaN
4,27656.0,2022-01-01,3.0,Внш Давид,Преобразователь ИД3,30358.0,Электроматериалы,шт,1.0,4070.0,4070.0,NaT,NaN,ООО КОНСТАНТА Счет №2316 от 14 декабря 2021 г.,NaN,Кайрокум,NaN

In [14]:
## Change the Column names (all of the columns)
jan_feb_2022_reports.columns["Наименование", "Сумма по полю Сумма","Сумма по полю Кол-во","Empty","Наименование2","Сумма о полю Сумма2","Diff6", "Whatever"]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [7]:
reportsjan_feb.head()

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
2,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 100/6кВТ,30365.0,Электроматериалы,шт,1.0,42275.0,42275.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Себистон,NaN
3,27655.0,2022-01-01,2.0,Внш Давид,Компас Горно геологический ГГК,30362.0,Ос Средства,шт,5.0,2700.0,13500.0,NaT,NaN,ООО СПЕЦСНАБ ПГС Счет №21122010 от 20.12.2021,NaN,Рогун УБР,NaN
4,27656.0,2022-01-01,3.0,Внш Давид,Преобразователь ИД3,30358.0,Электроматериалы,шт,1.0,4070.0,4070.0,NaT,NaN,ООО КОНСТАНТА Счет №2316 от 14 декабря 2021 г.,NaN,Кайрокум,NaN