In [85]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib as plt

ModuleNotFoundError: No module named 'matplotlib'

In [5]:
eths = pd.read_csv("https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/master/Python/Pandas/10-Datetime-Timeseries/ETH_1h.csv")

In [81]:
eths.head()

,Symbol,Open,High,Low,Close,Volume,Day_Name
Date,,,,,,,
2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday

In [84]:
# Plot - I should Install Matplotlib
highs.plot()

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.

In [80]:
# Resampling Weekly
eths["Close"].resample("W").min()

Date
2017-07-02    256.81
2017-07-09    233.45
2017-07-16    134.32
2017-07-23    159.53
2017-07-30    180.00
               ...
2020-02-16    218.32
2020-02-23    245.78
2020-03-01    212.50
2020-03-08    199.46
2020-03-15     98.88
Freq: W-SUN, Name: Close, Length: 142, dtype: float64

In [82]:
# Resampling Daily
high = eths["High"].max()
highs = eths["High"].resample("D").max()

In [75]:
# How to get mean for High
#GET Median for Low
# Mean for Close
# Sum for Volume
# between date times
eths["2019":"2020"].agg({"Open":"mean", "High":"median", "Low":"mean", "Volume":"sum"})

Open      1.835510e+02
High      1.756500e+02
Low       1.823756e+02
Volume    1.067547e+10
dtype: float64

In [73]:
# Get a mean and median within a timeframe
eths["2019-02-01" :"2019-09-01"].mean()

C:\Users\User-PC\AppData\Local\Temp\ipykernel_17188\3719971378.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  eths["2019-02-01" :"2019-09-01"].mean()

Open      1.956569e+02
High      1.968496e+02
Low       1.943625e+02
Close     1.956698e+02
Volume    1.186072e+06
dtype: float64

In [70]:
## Getting DATES between
filtering_via_licing = eths["2019-01-01" : "2020-01-01"]
filtering_via_licing.head()

,Symbol,Open,High,Low,Close,Volume,Day_Name
Date,,,,,,,
2020-01-01 23:00:00,ETHUSD,129.77,130.27,129.24,130.19,215362.64,Wednesday
2020-01-01 22:00:00,ETHUSD,131.41,131.41,129.36,129.77,411940.73,Wednesday
2020-01-01 21:00:00,ETHUSD,131.73,131.99,130.97,131.41,1168999.08,Wednesday
2020-01-01 20:00:00,ETHUSD,131.34,131.87,131.23,131.73,162346.84,Wednesday
2020-01-01 19:00:00,ETHUSD,131.64,131.72,131.15,131.34,167992.84,Wednesday

In [63]:
eths.set_index(["Date"], inplace=True)
eths

KeyError: "None of ['Date'] are in the columns"

In [58]:
# Show Dates between 2020 and 2019
between_dates = (eths["Date"] <= "2020") & (eths["Date"] >= "2019")
eths.loc[between_dates]

,Date,Symbol,Open,High,Low,Close,Volume,Day_Name
1748,2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday
1749,2019-12-31 23:00:00,ETHUSD,128.33,128.69,128.14,128.54,440678.91,Tuesday
1750,2019-12-31 22:00:00,ETHUSD,128.38,128.69,127.95,128.33,554646.02,Tuesday
1751,2019-12-31 21:00:00,ETHUSD,127.86,128.43,127.72,128.38,350155.69,Tuesday
1752,2019-12-31 20:00:00,ETHUSD,127.84,128.34,127.71,127.86,428183.38,Tuesday
...,...,...,...,...,...,...,...,...
10504,2019-01-01 04:00:00,ETHUSD,130.75,133.96,130.74,131.96,2791135.37,Tuesday
10505,2019-01-01 03:00:00,ETHUSD,130.06,130.79,130.06,130.75,503732.63,Tuesday
10506,2019-01-01 02:00:00,ETHUSD,130.79,130.88,129.55,130.06,838183.43,Tuesday
10507,2019-01-01 01:00:00,ETHUSD,131.62,131.62,130.77,130.79,434917.99,Tuesday
10508,2019-01-01 00:00:00,ETHUSD,130.53,131.91,130.48,131.62,1067136.21,Tuesday

In [51]:
# Show only Dates that are >= than 2020
eths[eths["Date"] >= "2020"]

,Date,Symbol,Open,High,Low,Close,Volume,Day_Name
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
1744,2020-01-01 04:00:00,ETHUSD,129.57,130.00,129.50,129.56,702786.82,Wednesday
1745,2020-01-01 03:00:00,ETHUSD,130.37,130.44,129.38,129.57,496704.23,Wednesday
1746,2020-01-01 02:00:00,ETHUSD,130.14,130.50,129.91,130.37,396315.72,Wednesday
1747,2020-01-01 01:00:00,ETHUSD,128.34,130.14,128.32,130.14,635419.40,Wednesday
1748,2020-01-01 00:00:00,ETHUSD,128.54,128.54,128.12,128.34,245119.91,Wednesday

In [47]:
# How to get maximum and minimum of the Date
# eths["Date"].min()
# eths["Date"].max()
# Find a range
eths["Date"].min() -eths["Date"].max()

Timedelta('-987 days +15:00:00')

In [34]:
# We have converted it to the Date as Datatype
eths["Date"] = pd.to_datetime(eths["Date"], format = "%Y-%m-%d %I-%p",errors="coerce")
eths

                     Date  Symbol    Open    High     Low   Close      Volume
0     2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1     2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2     2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3     2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4     2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                   ...     ...     ...     ...     ...     ...         ...
23669 2017-07-01 15:00:00  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670 2017-07-01 14:00:00  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671 2017-07-01 13:00:00  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672 2017-07-01 12:00:00  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673 2017-07-01 11:00:00  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [43]:
## Get a Day_name()for the column
#eths["Date"].dt.day_name()
## Create a column where you can see the daynames
eths["Day_Name"] =eths["Date"].dt.day_name()

In [44]:
eths

,Date,Symbol,Open,High,Low,Close,Volume,Day_Name
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [8]:
# As we can see our date column is in a str or object data type. We have to fix it
eths.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23674 entries, 0 to 23673
Data columns (total 7 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Date    23674 non-null  object
 1   Symbol  23674 non-null  object
 2   Open    23674 non-null  float64
 3   High    23674 non-null  float64
 4   Low     23674 non-null  float64
 5   Close   23674 non-null  float64
 6   Volume  23674 non-null  float64
dtypes: float64(5), object(2)
memory usage: 1.3+ MB