In [2]:
import pandas as pd
import numpy as np

In [74]:
reportsjan_feb =pd.read_excel("For_Pandas_Original_DF.xlsx", sheet_name = "внешный")
jan_feb_2022_reports = pd.read_excel("For_Pandas_Original_DF.xlsx")
reportsjan_feb.head(2)
#reportsjan_feb.dtypes

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN

In [76]:
# Let's see and count the unique values
#see---- reportsjan_feb["Поставщик"].unique()
# count---- reportsjan_feb["Поставщик"].nunique()

11

In [73]:
# Let's Cast our Datatypes
reportsjan_feb.dtypes
# Let's change column ["Абрев"] to string
#reportsjan_feb["Серия"].value_counts()
#reportsjan_feb["Серия"].map({"24шт":"new"})
reportsjan_feb["МНН"].astype(str)
reportsjan_feb.dtypes

Код                    float64
Дата            datetime64[ns]
№ док                  float64
Поставщик               object
Наименование            object
Абрев                  float64
Тов группа              object
Ед Изм                  object
Кол-во                 float64
Цена                   float64
Сумма                  float64
Срок            datetime64[ns]
Серия                   object
Произ.                  object
МНН                    float64
Вопросы                 object
Unnamed: 16             object
dtype: object

In [44]:
# Let's fill our missing values for the Dataframe 
reportsjan_feb["Серия"].fillna(0,inplace =True)
reportsjan_feb.isna().sum()

Код               3
Дата              3
№ док             3
Поставщик         3
Наименование      3
Абрев             3
Тов группа       27
Ед Изм            3
Кол-во            3
Цена              3
Сумма             0
Срок            247
Серия             0
Произ.            4
МНН             259
Вопросы           3
Unnamed: 16     255
dtype: int64

In [36]:
# Let's check how many nans are in our Dataframe
reportsjan_feb.isna().sum()
# Let's drop one of the non-needed columns
#reportsjan_feb.drop(columns=["Unnamed: 16"], inplace =True)
reportsjan_feb.isna().sum()

Код               3
Дата              3
№ док             3
Поставщик         3
Наименование      3
Абрев             3
Тов группа       27
Ед Изм            3
Кол-во            3
Цена              3
Сумма             0
Срок            247
Серия           249
Произ.            4
МНН             259
Вопросы           3
dtype: int64

In [27]:
# We have changed the missing values that were different to nan and dropped them
reportsjan_feb["Произ."].value_counts()
reportsjan_feb.replace(",", np.nan, inplace=True)
reportsjan_feb.dropna(axis ="index", how="any", subset =["Произ."])
reportsjan_feb["Произ."].value_counts()

Hexing Electrical Co., Ltd  Контракт:TGEM/HEXING-001  Спец.1                            66
ООО Фарами групп  Контракт:№SOLYXIL-ЕКБ-02 от 17.09.2021г. Спец.3                       25
Shanghai Jiameng International Trading Company Ltd.  Контракт:TGEM/MELEC-001  Спец.4    19
Shanghai Electric Machinary Co., Ltd  Контракт:06.10.2020 Спец.1                        18
STP Global Cable - Азербайджан  Контракт:№0135/11102021-KZ  Спец.1                      10
HENAN LIMING HEAVY INDUSTRY MACHINERY SALES Co.,LTD.  Контракт:12.10.2020 Спец.1         7
ООО "Элпартнер" Контракт:№643/82861921/20059 Спец.7                                      7
ООО "ФАРАМИ ГРУПП", Москва  Контракт:№ФГ/ЕКБ-01 от 23.06.2021  Спец.1                    6
ООО Нокили Талко  Контракт:TGEM/TALKO-001  Спец.1                                        6
Shanghai Chance Industry Co Ltd.  Контракт:TGEM/CHANCE-001  Спец.3                       5
HENAN LIMING HEAVY INDUSTRY MACHINERY SALES Co.,LTD.  Контракт:12.10.2020 Спец.2         5
ООО"ЭТК Полипроф" /Россия/Москва  Счет на оплату №4401 от 17.12.2021 г.                  5
ООО "Элпартнер" Контракт:№643/82861921/20059 Спец.6                                      4
Yongce Group Co., Ltd  Контракт:28.12.2020                                               4
Henan Yuantai Crane Machinery Import & Export Co., Ltd.  Контракт:14.01.2021             4
АО "ПЕРГАМ-ИНЖИНИРИНГ"-Россия  Контракт:№ТГЭМ-ПЕРГАМ-001  Спец.1                         4
Global engineering and construction FZE  Контракт:№TG-2021-9 Спец.10                     4
ООО КОНСТАНТА  Счет №2316 от 14 декабря 2021 г.                                          4
WENZHOU MAOCHEN ELECTRIC POWER CO.,LTD. Контракт:06/06/2020 Спец.2                       3
Shandong Tianhai New Materials Engineering Co, Ltd.  Контракт:28.12.2020 Спец.2          3
ООО Бинхен Бау  Контракт:№249/2020 Спец.4                                                3
ФАРАМИ ГРУПП-Россия  Договор Поставки № ФГ/ЕКБ-03 от 28.09.2021  Спецификация №3         3
Чирчикский трансформаторный завод  Контракт:TGEM/CHTZ-001  Спецификация №2               3
Shandong Tianhai New Materials Engineering Co, Ltd.  Контракт:28.12.2020 Спец.3          2
Внт другие                                                                               2
ФАРАМИ ГРУПП-Россия  Контракт:№ SOLYXIL/ЕКБ-04  Спецификация №5                          2
ООО "Элпартнер" Счет №ТП-188 от 22.12.2021г.                                             2
TG-2021-6 Спец4                                                                          2
ООО ТЭСТО РУС  Счет-договор №28990 от 20.12.2021                                         2
Камкабель Контракт:TJ/33/20040 от 25.11.2020 г                                           2
ООО СПЕЦСНАБ ПГС  Счет №21122010 от 20.12.2021                                           1
ООО Техмаш Экспорт                                                                       1
LEVI INSAAT TEKSTIL GIDA NAKLIVE ELEKTRONIK  Контракт:№ TGEM/LEVI-01 от 01.11.2021       1
WENZHOU MAOCHEN ELECTRIC POWER CO.,LTD. Контракт:06/06/2020 Спец.3                       1
SARAPUSH IRAN  Контракт:28.01.2021 Спец.2                                                1
ЧП Проминвестэнерго Контракт №80 от 08,10,2021 Спец 1                                    1
ОАО "Металлист" Контракт:№ 103/27-19 Спец.1                                              1
ООО "Полипласт-Уралсиб" Контракт:№001/2020 от 09.01.2020г.                               1
Name: Произ., dtype: int64

In [21]:
# Let's drop an NA from a multiple columns
reportsjan_feb.dropna(axis="index", how="any", subset=["Произ.","Серия"], inplace = True)
reportsjan_feb

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
22,28470.0,2022-01-01,1.0,Внш Хувайдо,Двутавер №25 Б1,11197.0,Стройматериал,кг,7402.0,19.4,143598.796875,2040-01-01,24шт,",",NaN,Рогун УБР,NaN
56,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №41,2941.0,Спец одежда,пар,10.0,247.0,2470.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
57,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №42,2942.0,Спец одежда,пар,600.0,247.0,148200.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
58,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №43,2943.0,Спец одежда,пар,730.0,247.0,180310.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
59,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №44,2944.0,Спец одежда,пар,10.0,247.0,2470.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
60,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №45,2945.0,Спец одежда,пар,10.0,247.0,2470.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
76,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимний №41,2941.0,Спец одежда,пар,390.0,247.0,96330.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо
77,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимний №44,2944.0,Спец одежда,пар,90.0,247.0,22230.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо
78,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимный №40,3035.0,Спец одежда,пар,350.0,247.0,86450.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо
79,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимний №45,2945.0,Спец одежда,пар,20.0,247.0,4940.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо

In [19]:
# Let's drop an NA from a specific column
reportsjan_feb.dropna(axis="index", how="any", subset=["Серия"], inplace = True)
reportsjan_feb

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
22,28470.0,2022-01-01,1.0,Внш Хувайдо,Двутавер №25 Б1,11197.0,Стройматериал,кг,7402.0,19.4,143598.796875,2040-01-01,24шт,",",NaN,Рогун УБР,NaN
56,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №41,2941.0,Спец одежда,пар,10.0,247.0,2470.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
57,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №42,2942.0,Спец одежда,пар,600.0,247.0,148200.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
58,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №43,2943.0,Спец одежда,пар,730.0,247.0,180310.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
59,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №44,2944.0,Спец одежда,пар,10.0,247.0,2470.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
60,27658.0,2022-01-10,2.0,Внт Фирдавс,Обув зимний №45,2945.0,Спец одежда,пар,10.0,247.0,2470.000000,2040-01-01,новый,",",NaN,Почему Внш,NaN
76,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимний №41,2941.0,Спец одежда,пар,390.0,247.0,96330.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо
77,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимний №44,2944.0,Спец одежда,пар,90.0,247.0,22230.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо
78,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимный №40,3035.0,Спец одежда,пар,350.0,247.0,86450.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо
79,28271.0,2022-01-25,1.0,Внт Фирдавс,Обув зимний №45,2945.0,Спец одежда,пар,20.0,247.0,4940.000000,2040-01-01,новый,",",NaN,Барои чи Внш,Барои хамаи лоияхо

In [7]:
# Drop Na from DF
reportsjan_feb.dropna(axis="index",how="any")
reportsjan_feb.head(2)

,Код,Дата,№ док,Поставщик,Наименование,Абрев,Тов группа,Ед Изм,Кол-во,Цена,Сумма,Срок,Серия,Произ.,МНН,Вопросы,Unnamed: 16
0,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 250/10кВТ,30363.0,Электроматериалы,шт,1.0,65770.0,65770.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN
1,27654.0,2022-01-01,1.0,Внш Давид,Трансформатор ТМГ 630/10кВТ,30364.0,Электроматериалы,шт,1.0,118255.0,118255.0,NaT,NaN,Чирчикский трансформаторный завод Контракт:TG...,NaN,Нуробод Оби гарм,NaN